### ISSUE TITLE
boots.nbt.value.Enchantments.some is not a function

### ISSUE THREAD

**Issue by octo-kumo** [PrismarineJS/prismarine-physics#15]
```
../node_modules/prismarine-physics/index.js:599
    this.depthStrider = boots && boots.nbt.value.Enchantments && boots.nbt.value.Enchantments.some(x => x.id === mcData.enchantmentsByName.depth_strider.id)
                                                                                              ^

TypeError: boots.nbt.value.Enchantments.some is not a function
    at new PlayerState (../node_modules/prismarine-physics/index.js:599:95)
    at Timeout.doPhysics [as _onTimeout] (../node_modules/mineflayer/lib/plugins/physics.js:61:32)
    at listOnTimeout (internal/timers.js:551:17)

    at processTimers (internal/timers.js:494:7)
```

I suspect this has to do with 1.16

**Comment by rom1504** [comment]
Did you try with a recent node version?

**Comment by jackklika** [comment]
I'm having a similar problem, using node 14.1.0.

```
../prismarine-gameplay/node_modules/prismarine-physics/index.js:599
    this.depthStrider = boots && boots.nbt.value.Enchantments && boots.nbt.value.Enchantments.some(x => x.id === mcData.enchantmentsByName.depth_strider.id)
                                           ^

TypeError: Cannot read property 'value' of null
    at new PlayerState (/home/j/git/prismarine-gameplay/node_modules/prismarine-physics/index.js:599:44)
    at Timeout.doPhysics [as _onTimeout] (/home/j/git/prismarine-gameplay/node_modules/mineflayer/lib/plugins/physics.js:61:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by Karang** [comment]
Looks like there is a missing null check (nbt can be null if its a simple item). @IdanHo

**Comment by IdanHo** [comment]
yep, missed that, will open a pull to fix it, sorry.
