### ISSUE TITLE
enchantments.find is undefined

### ISSUE THREAD

**Issue by hexatester** [PrismarineJS/prismarine-physics#25]
Version:
"mineflayer": "^2.28.1"
"prismarine-physics": "^1.0.4", <- package-lock.json

Error:
```
D:\Projects\test-bot\node_modules\prismarine-physics\index.js:602
const depthEnchant = enchantments.find(x => x.id === mcData.enchantmentsByName.depth_strider.id || x.id === ('minecraft:' + mcData.enchantmentsByName.depth_strider.name))
                                        ^

TypeError: Cannot read property 'find' of undefined
    at new PlayerState (D:\Projects\test-bot\node_modules\prismarine-physics\index.js:602:41)
    at Timeout.doPhysics [as _onTimeout] (D:\Projects\test-bot\node_modules\mineflayer\lib\plugins\physics.js:61:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by rom1504** [comment]
Yeah update your dependencies (npm update --depth=9999 )

**Comment by hexatester** [comment]
Thanks.
